apiVersion: v1
kind: Secret
metadata:
  name: skywatch-secrets
type: Opaque
stringData:
  DATABASE_URL: REPLACE_WITH_ACTUAL_URL
  POSTGRES_USER: REPLACE_WITH_USER
  POSTGRES_PASSWORD: REPLACE_WITH_PASSWORD
  POSTGRES_DB: REPLACE_WITH_DB
