apiVersion: v1
kind: Service
metadata:
  name: skywatch-service
spec:
  selector:
    app: skywatch-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
